version: '3.1'

services:

  db:
    image: mysql:8.0.21
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mlfo1234
      MYSQL_DATABASE: modelrepo
    ports:
      - "3306:3306"
    volumes:
      - ./modelrepo.sql:/modelrepo.sql 
